add pod context security
pmint93/helm-charts pull request #141
Opened 2024-10-31 14:18 UTC by pierremahot

add pod context security and set README to the real info

2024-11-01 09:23 UTC, pmint93 reviewed
Please also bump the chart version in Chart.yaml

2024-11-01 09:23 UTC, pmint93 commented on charts/metabase/templates/deployment.yaml
> +    {{- .Values.securityContext | toYaml | nindent 8 }}
Shouldn't it be `.Values.podSecurityContext` ?

2024-11-09 01:34 UTC, pmint93 commented on charts/metabase/templates/deployment.yaml
> +    {{- .Values.securityContext | toYaml | nindent 8 }}
@pierremahot

2024-11-10 23:35 UTC, pierremahot commented on charts/metabase/templates/deployment.yaml
> +    {{- .Values.securityContext | toYaml | nindent 8 }}
No is at the pod level and not the container level but it's called the same and it's not the same type of objects refert to the lube api full doc https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#podspec-v1-core

2024-11-10 23:35 UTC, pierremahot commented on charts/metabase/templates/deployment.yaml
> +    {{- .Values.securityContext | toYaml | nindent 8 }}
My bad

2024-11-12 02:46 UTC, pmint93 requested changes

2024-11-12 02:46 UTC, pmint93 commented on charts/metabase/templates/deployment.yaml
> +    {{- .Values.podSecurityContext | toYaml | nindent 8 }}
@pierremahot it seem we're missing `{{ - end }}` here

2024-11-14 08:28 UTC, pierremahot commented on charts/metabase/templates/deployment.yaml
> +    {{- .Values.podSecurityContext | toYaml | nindent 8 }}
I have added the missing  `{{- end }}`

2024-11-14 16:33 UTC, pmint93 approved these changes

2024-11-14 16:33 UTC, pmint93 commented
Thanks for contributing !

2024-11-14 16:33 UTC, merged