feat(config): add support for config.yaml file
pmint93/helm-charts pull request #45
Opened 2022-11-11 14:19 UTC by hazzadous

Support for specifying a config.yaml config file was added
[here](https://github.com/metabase/metabase/pull/25986/files). I'm not
sure if this is the best way to add support for this, but would love to
have the ability to specify the databases as part of the Helm Chart
values.

2022-11-18 13:27 UTC, ellie commented
Hey @pmint93! I've bumped the chat version + would love to see this merged 🙏  

>  From which version this config file was supported ? Can we also bump the metabase version accordingly ?

Looks like the change was added ~30 days ago: https://github.com/metabase/metabase/pull/25986

But I can't see it in the latest release :(

2022-11-18 16:43 UTC, hazzadous commented
Hah thanks @ellie  🤞 it makes it in the next release. #untested

2022-11-21 00:58 UTC, pmint93 commented
@hazzadous @ellie So I think we should wait for the release & official document of how to properly configure it

2022-12-10 09:11 UTC, pmint93 requested changes
The [release v0.45.1](https://www.metabase.com/releases/Metabase-0.45) has been out with instruction to configure it to load config file

And with #49 has been merged, we have some conflicts that need resolved

2025-05-22 09:00 UTC, closed without merging