Add new property `log4j2XML`
pmint93/helm-charts pull request #53
Opened 2022-12-28 16:55 UTC by sebglon

Fix issue: https://github.com/pmint93/helm-charts/issues/52

2022-12-29 08:07 UTC, ClementGautier requested changes

2022-12-29 08:07 UTC, ClementGautier commented on charts/metabase/templates/deployment.yaml
> +            {{- if .Values.log4j2XML }}
You will have a conflict if you pass both log4j2XML and log4jProperties. I suggest you simply modify the condition on line 197 like this: `{{- if .Values.log4jProperties or .Values.log4j2XML }}`

2022-12-29 08:07 UTC, ClementGautier commented on charts/metabase/templates/deployment.yaml
> +        {{- if .Values.log4j2XML}}
Same comment, this time you can probably get around with something like this:
```
        {{- if .Values.log4jProperties or .Values.log4j2XML }}
        - name: config
          configMap:
            name: {{ template "metabase.fullname" . }}-config
            items:
            {{- if .Values.log4jProperties}}
            - key: log4j.properties
              path: log4j.properties
            {{- end }}
            {{- if .Values.log4j2XML}}
            - key: log4j2.xml
              path: log4j2.xml
            {{- end }}
        {{- end }}
```

2022-12-29 08:29 UTC, sebglon commented on charts/metabase/templates/deployment.yaml
> +            {{- if .Values.log4j2XML }}
Fixed

2022-12-29 08:29 UTC, sebglon commented on charts/metabase/templates/deployment.yaml
> +        {{- if .Values.log4j2XML}}
Fixed

2022-12-29 09:03 UTC, ClementGautier approved these changes

2022-12-31 07:34 UTC, pmint93 approved these changes

2022-12-31 07:34 UTC, merged