[charts/metabase] Add documentation for monitoring.serviceMonitor.enabled
pmint93/helm-charts pull request #91
Opened 2023-12-13 13:41 UTC by eidottermihi

2023-12-14 08:50 UTC, pmint93 requested changes

2023-12-14 08:50 UTC, pmint93 commented on charts/metabase/README.md
> +| monitoring.serviceMonitor.enabled               | Enable OpenShift ServiceMonitor resource for prometheus scraping           | false             |
This is not a big deal but, I want it to be clear that ServiceMonitor is not exclusive to OpenShift. Actually OpenShift is using PrometheusOperator so there is a resource kind: ServiceMonitor

2023-12-16 12:13 UTC, eidottermihi commented on charts/metabase/README.md
> +| monitoring.serviceMonitor.enabled               | Enable OpenShift ServiceMonitor resource for prometheus scraping           | false             |
You're right, removed OpenShift.

2023-12-16 12:34 UTC, pmint93 approved these changes

2023-12-16 12:34 UTC, merged